### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by thomasaarholt** [pymontecarlo/pymontecarlo-casino2-gui#1]
Hi there!

I've been looking for some better way of either interfacing with Casino or having it replaced altogether with modern software. I thought I'd just ask what the status of this project is, and what is the intention with it :)

(Best regards, someone who spends time manually exporting data from multiple datasets with varying voltage in Casino)

**Comment by drix00** [comment]
Hi Thomas,

You have to check the main project to have doc.
http://pymontecarlo.readthedocs.io/en/latest/

You should be able to install it from pypi or I can send you a dropbox link to a pakaged program if you use window.

If you just want to export the data from .cas file, check out the project pycasinotools, which read and write .sim/.cas files:
https://github.com/drix00/pycasinotools

Regards,
Hendrix
